name = "Better MC [FORGE] BMC4"
author = "LunaPixelStudios"
version = "v36"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46de85336cdf5f1615bed87c3f9b47c48b0fbee557c013469bdc1becf7617da0"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
