name = "Better Minecraft Fixed"
author = "Sliden101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1e56e06957aa9eb33bd555bb032ef4e0685887e16d6c7727c7cfe83c8823d4c"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
