name = "absoluteCinema"
author = "sliden101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f779ef31b56cf03c2d74c8475956efd1bf957dc87813d60f7be40fefa2b8a0a"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
