name = "absoluteCinema"
author = "sliden101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71816423ec1a63abcb6037d067b341abf684a545104ab3650f3cd371c650763d"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
